import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import vm from "node:vm";

const previewSource = readFileSync(new URL("../CommunityVideoSelector.js", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const wizardSource = readFileSync(new URL("../SetupWizard.js", import.meta.url), "utf8");
const effectBody = (source, marker, ending) => {
  const markerIndex = source.indexOf(marker);
  const start = source.indexOf("useEffect(() => {", markerIndex);
  const end = source.indexOf(ending, start);
  assert.ok(markerIndex >= 0 && start > markerIndex && end > start);
  return source.slice(start + "useEffect(() => {".length, end);
};
const effects = {
  synced: effectBody(previewSource, "// 일반 모드: YouTube IFrame", "  }, [useHelper, videoId, startTime, skipSegments, isAutoGenerated]);"),
  simple: effectBody(previewSource, "// 일반 모드: YouTube\n", "  }, [useHelper, videoId]);"),
  wizard: effectBody(wizardSource, "// Initialize YouTube Player API", "  }, []);"),
};

const createEnvironment = ({ yt, readyCallback } = {}) => {
  let nextId = 0;
  const timeouts = new Map();
  const intervals = new Map();
  const players = [];
  const node = { innerHTML: "", appendChild() {} };
  const window = { YT: yt, onYouTubeIframeAPIReady: readyCallback, location: { origin: "https://example.test" } };
  const context = vm.createContext({
    window, console,
    useHelper: false, videoId: "test-video", startTime: 0, skipSegments: [], isAutoGenerated: false,
    containerRef: { current: node }, playerContainerRef: { current: node },
    playerRef: { current: null }, playerIdRef: { current: "wizard-player" }, syncIntervalRef: { current: null },
    setIsReady() {}, setPlayerReady() {},
    Spicetify: { Player: { addEventListener() {}, removeEventListener() {} } },
    document: {
      createElement: () => ({ style: {} }),
      getElementById: () => null,
      getElementsByTagName: () => [{ parentNode: { insertBefore() {} } }],
    },
    setTimeout(callback, delay) { const id = ++nextId; timeouts.set(id, { callback, delay }); return id; },
    clearTimeout: (id) => timeouts.delete(id),
    setInterval(callback, delay) { const id = ++nextId; intervals.set(id, { callback, delay }); return id; },
    clearInterval: (id) => intervals.delete(id),
  });
  return {
    window, timeouts, intervals, players,
    mount(name) { return vm.runInContext(`(() => { ${effects[name]} })()`, context); },
    loadApi() {
      window.YT = { Player: function Player(id, options) {
        this.id = id;
        this.options = options;
        this.destroyed = false;
        this.destroy = () => { this.destroyed = true; };
        players.push(this);
      } };
    },
    tick() {
      const [id, timer] = timeouts.entries().next().value;
      timeouts.delete(id);
      timer.callback();
    },
  };
};

for (const name of ["synced", "simple", "wizard"]) {
  test(`${name} cancels unavailable-API retry when closed and ignores an already queued callback`, () => {
    const environment = createEnvironment({ yt: {} });
    const cleanup = environment.mount(name);
    assert.equal(environment.timeouts.size, 1);
    const timer = [...environment.timeouts.values()][0];
    assert.equal(timer.delay, name === "wizard" ? 200 : 100);
    cleanup();
    assert.equal(environment.timeouts.size, 0);
    assert.equal(environment.intervals.size, 0);
    timer.callback();
    assert.equal(environment.timeouts.size, 0);
    environment.loadApi();
    timer.callback();
    assert.equal(environment.players.length, 0);
  });

  test(`${name} still initializes after delayed API loading while mounted and destroys its player`, () => {
    const environment = createEnvironment({ yt: {} });
    const cleanup = environment.mount(name);
    environment.tick();
    assert.equal(environment.timeouts.size, 1);
    environment.loadApi();
    environment.tick();
    assert.equal(environment.players.length, 1);
    assert.equal(environment.players[0].options.videoId, name === "wizard" ? "9bZkp7q19f0" : "test-video");
    assert.equal(environment.timeouts.size, 0);
    cleanup();
    assert.equal(environment.players[0].destroyed, true);
  });
}

test("wizard preserves the existing API-ready callback and restores it when closed", () => {
  const calls = [];
  function previous(...args) { calls.push({ receiver: this, args }); }
  const environment = createEnvironment({ readyCallback: previous });
  const cleanup = environment.mount("wizard");
  const callback = environment.window.onYouTubeIframeAPIReady;
  environment.loadApi();
  callback("ready");
  assert.equal(calls.length, 1);
  assert.strictEqual(calls[0].receiver, environment.window);
  assert.deepEqual(calls[0].args, ["ready"]);
  assert.equal(environment.players.length, 1);
  cleanup();
  assert.strictEqual(environment.window.onYouTubeIframeAPIReady, previous);
});

test("wizard cleanup retains a newer API callback and prevents late player creation", () => {
  const environment = createEnvironment();
  const cleanup = environment.mount("wizard");
  const ownCallback = environment.window.onYouTubeIframeAPIReady;
  const newerCallback = () => ownCallback();
  environment.window.onYouTubeIframeAPIReady = newerCallback;
  cleanup();
  assert.strictEqual(environment.window.onYouTubeIframeAPIReady, newerCallback);
  environment.loadApi();
  newerCallback();
  assert.equal(environment.players.length, 0);
  assert.equal(environment.timeouts.size, 0);
});
